### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by tthsn** [blockstack/blockstack-stats#2]
$ npm install 

...
npm http 304 https://registry.npmjs.org/watchify
npm ERR! git clone ssh://git@github.com/blockstack/blockstack-bootstrap.git Cloning into bare repository '/home/me/.npm/_git-remotes/ssh-git-github-com-blockstack-blockstack-bootstrap-git-f35841e2'...
npm ERR! git clone ssh://git@github.com/blockstack/blockstack-bootstrap.git Permission denied (publickey).
npm ERR! git clone ssh://git@github.com/blockstack/blockstack-bootstrap.git fatal: Could not read from remote repository.
npm ERR! git clone ssh://git@github.com/blockstack/blockstack-bootstrap.git 
npm ERR! git clone ssh://git@github.com/blockstack/blockstack-bootstrap.git Please make sure you have the correct access rights
npm ERR! git clone ssh://git@github.com/blockstack/blockstack-bootstrap.git and the repository exists.
npm ERR! Error: Command failed: Cloning into bare repository '/home/me/.npm/_git-remotes/ssh-git-github-com-blockstack-blockstack-bootstrap-git-f35841e2'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.19.0-66-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/me/dev/src/github.com/blockstack/blockstack-stats
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code 128
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/me/dev/src/github.com/blockstack/blockstack-stats/npm-debug.log
npm ERR! not ok code 0

**Comment by tthsn** [comment]
npm install ok, after remove the nodejs and npm provided by ubuntu 14.04 64bit, and replace node js with the following versions:
$ node --version
v4.5.0
$ npm --version
2.15.9
